# -*- coding: utf-8 -*-
"""titanic-data-science-pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KZCEK9QvUOiA0k7trgc_SGiS8KX-k5Vs
"""

import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestClassifier

data = pd.read_csv(r'/content/cleaned_titanic.csv')

data.head()

#moving survived column to the end

survived = data.pop('Survived')
data['Survived'] = survived

data.head()

x = data.iloc[::-1]
y = data['Survived']

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

lr = LogisticRegression()
lr.fit(x_train, y_train)
lr.score(x_train, y_train)

rfc = RandomForestClassifier(n_estimators=100)
rfc.fit(x_train, y_train)
rfc.score(x_train, y_train)







